### ISSUE TITLE
Debian and PyPi Packages

### ISSUE THREAD

**Issue by 132ikl** [132ikl/liteshort#18]
This issue is to discuss a possible Debian package which would automate the install process.

**Comment by 132ikl** [comment]
@eibex thoughts?

**Comment by eibex** [comment]
Not a bad idea, it would make the installation much easier for those who are not too familiar with venv, uWSGI etc. Or just technically inclined people since even the systemd service could be potentially installed automatically.

Though I never compiled a *.deb myself so I wouldn't know how to help.

**Comment by 132ikl** [comment]
I've decided to expand this into a PyPi package and a Debian package. The PyPi package will handle all the basic program parts, including the main code, executable, and config. The Debian package will handle the system-level parts, such as uwsgi config and the system service. The implementation details are in the `CONVENTIONS` file in the `feature/package` branch. That also lays out some other design philosophies which should be met by 2.0, namely readable code and simple to install (deb and PyPi package should remedy this).
